lang: ru
title: Михаил Юдин
headline: Михаил Юдин
author:
  name: Михаил Юдин
  email: fagci.nsk@gmail.com
  jobTitle: Web Developer
  image: /assets/img/ava.jpg
logo: /assets/img/favicon-full.png
description: >
  Я фронтенд разработчик, веду блог о вёрстке сайтов, оптимизации веб-приложений. Улучшаю пользовательский опыт, собираю лучшие практики в области веб-разработки.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikhail-yudin.ru"

username:
  github: fagcinsk
  telegram: fagci
  vk: fagci
  skype: silenceproject
  twitter: fagcinsk
  facebook: fagcinsk
  icq: 430468782
  pinterest: fagcinsk
  instagram: fagci.nsk

social: # jekyll-seo-tag
  name: Михаил Юдин
  links:
    - https://twitter.com/fagcinsk
    - https://github.com/fagcinsk
    - https://vk.com/fagci
    - https://www.facebook.com/fagcinsk
    - https://www.instagram.com/fagci.nsk/

webmaster_verifications:
  google: cYPYXSNeHCFhzx8wb_DhIoSC1GhqibLCVUEDbpFfdgI
  yandex: ea38c54b7e1b64ef

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'codehilite'

permalinks: pretty

leaflet: leaflet@1.5.1

target-blank:
  rel: external
  add_css_classes: ext-link

pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  title: ':title - страница :num'
  category: 'blog'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

collections:
  projects:
    output: true
    permalink: /projects/:title
  posts:
    output: true
    permalink: /blog/:categories/:title

autopages:
  enabled: false

  categories:
    enabled: false
    layouts: ['autopage_category.html']
    title: 'Записи в категории :cat'
    permalink: '/blog/:cat'

  collections:
    enabled: false

  tags:
    enabled: false

include:
  - _pages
  - _categories
  - _headers
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
  - .jekyll-cache
  - .sass-cache
  - _redirects
