lang: ru
title: Михаил Юдин
headline: Михаил Юдин
author:
  name: Михаил Юдин
  email: fagci.nsk@gmail.com
copyright: Михаил Юдин (fagci)
email: fagci.nsk@gmail.com
description: >
  Full-Stack developer. 
  Большую часть времени занимаюсь frontend разработкой, UX/UI.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikhail-yudin.ru" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  fagcinsk
telegram_username: fagci
vk_username: fagci
icq_username: 430468782
skype_username: silenceproject

social:
  name: Михаил Юдин
  links:
    - https://github.com/fagcinsk
    - https://vk.com/fagci

include: ['_pages']
# Build settings
#safe: true
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge

navigation: # Navigation links
  - {name: 'Главная', link: '/'}
  - {name: 'Проекты', link: '/projects/'}
  - {name: 'Обо мне', link: '/about/'}
  - {name: 'Контакты', link: '/contact/'}

permalinks: pretty
permalink: /:categories/:title/

categoryMap:
  frontend: Фронтенд
  backend: Бэкэнд
  lifehacks: Лайфхаки
  hardware: Железо
  linux: Linux
  android: Android
  trip: Путешествия

leaflet: leaflet@1.5.1

exiftag:
 sources:
   - photos
   - photos/multa-lake-trip

lazy_load_image:
  src_attr_name: data-src # [required] You need to specify the attributes to be saved for lazy loading
  # preload_image: /path/to/image # [optional] you can add a data uri or loading image as fallback src
  class_attr_values: # [optional] if you want to add custom class value, please add values
    - lazyload
  # ignore_selectors: # [optional] if you want to ignore applying lazy load image, please add selector (css or xpath)
  #   - ".ignore-lazy-image-load"
  #   - "/*[@class='ignore-lazy-image-load']"
  # additional_attrs: # [optional] if you want to add attributes, please add key value
  #   "data-size": auto 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
