lang: ru
title: Михаил Юдин
headline: Михаил Юдин
author:
  name: Михаил Юдин
  email: fagci.nsk@gmail.com
copyright: Михаил Юдин (fagci)
email: fagci.nsk@gmail.com
description: >
  Занимаюсь frontend разработкой, улучшаю пользовательский опыт. Рассказываю о железячных проектах, настройке сервера, полезных Android приложениях.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikhail-yudin.ru"

github_username:  fagcinsk
telegram_username: fagci
vk_username: fagci
icq_username: 430468782
skype_username: silenceproject

username:
  github: fagcinsk
  telegram: fagci
  vk: fagci
  skype: silenceproject
  twitter: fagcinsk
  facebook: fagcinsk
  icq: 430468782
  pinterest: fagcinsk

social:
  name: Михаил Юдин
  links:
    - https://github.com/fagcinsk
    - https://vk.com/fagci
    - https://www.facebook.com/fagcinsk

webmaster_verifications:
  google: cYPYXSNeHCFhzx8wb_DhIoSC1GhqibLCVUEDbpFfdgI
  yandex: ea38c54b7e1b64ef

include: ['_pages','_redirects','_projects']
# Build settings
#safe: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge

navigation: # Navigation links
  - {name: 'Проекты', link: '/projects/'}
  - {name: 'Обо мне', link: '/about/'}
  - {name: 'Контакты', link: '/contact/'}

permalinks: pretty
permalink: /:categories/:title/

categoryMap:
  frontend:
    name: Фронтенд
    description: "Материал, связанный с фронтовой частью веб-разработки: вёрстка, JavaScript, UX/UI в общем."
  backend:
    name: Бэкэнд
    description: "Бэкэндная частью веб-разработки: PHP, NodeJS, ..."
  lifehacks:
    name: Лайфхаки
    description: "Хитрости жизни"
  hardware:
    name: Железо
    description: "Железячные проекты: Arduino, STM32, всякие датчики, дисплеи, механизмы."
  linux:
    name: Linux
    description: "Администрирование Linux, настройка сервера, примеры настроек."
  android:
    name: Android
    description: "Приложения для Android, примеры использования приложений, обзоры, рекомендации."
  trip:
    name: Путешествия
    description: "Путешествия по необъятной планете =)"

category_layout: "category-index.html" # <- default value

leaflet: leaflet@1.5.1

exiftag:
 sources:
   - photos
   - photos/multa-lake-trip

lazy_load_image:
  src_attr_name: data-src # [required] You need to specify the attributes to be saved for lazy loading
  # preload_image: path/to/image # [optional] you can add a data uri or loading image as fallback src
  class_attr_values: # [optional] if you want to add custom class value, please add values
    - lazyload
  # ignore_selectors: # [optional] if you want to ignore applying lazy load image, please add selector (css or xpath)
  #   - ".ignore-lazy-image-load"
  #   - "/*[@class='ignore-lazy-image-load']"
  # additional_attrs: # [optional] if you want to add attributes, please add key value
  #   "data-size": auto 

autoprefixer:
  browsers:
    - last 2 versions

yandex_metrika:
  token: AgAAAAACBsTEAAXOQm6356MxwEN8vDlsI0f5t3g
  site_url: https://mikhail-yudin.ru/
  trim_last: " | Михаил Юдин"


pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - страница :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
  - .jekyll-cache
