title: Михаил Юдин, веб разработчик
email: fagci.nsk@gmail.com
description: Full-Stack developer. Большую часть времени занимаюсь frontend разработкой, UX/UI.
copyright: fagci

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  fagcinsk
telegram_username: fagci

lang: ru

# Build settings
markdown: kramdown
remote_theme: janczizikow/sleek

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

navigation: # Navigation links
  - {name: 'Главная', link: '/'}
  - {name: 'Обо мне', link: '/about'}
  - {name: 'Контакты', link: '/contact'}
  
headline: Михаил Юдин | Персональный блог  
  
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
