lang: ru
title: Михаил Юдин
headline: Михаил Юдин
author: fagci
copyright: Михаил Юдин (fagci)
email: fagci.nsk@gmail.com
description: >
  Full-Stack developer. 
  Большую часть времени занимаюсь frontend разработкой, UX/UI.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikhail-yudin.ru" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  fagcinsk
telegram_username: fagci
vk_username: fagci
icq_username: 430468782
skype_username: silenceproject

social:
  name: Михаил Юдин
  links:
    - https://github.com/fagcinsk
    - https://vk.com/fagci

# Build settings
#safe: true
paginate: 10
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge

navigation: # Navigation links
  - {name: 'Главная', link: '/'}
  - {name: 'Обо мне', link: '/about/'}
  - {name: 'Контакты', link: '/contact/'}

permalinks: pretty
permalink: /:categories/:title/

categoryMap:
  frontend: Фронтенд
  backend: Бэкэнд
  lifehacks: Лайфхаки
  hardware: Железо
  linux: Linux
  android: Android
  trip: Путешествия

leaflet: leaflet@1.5.1

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 300
    - width: 600
    - width: 900
    - width: 1200
    - width: 1400
    - width: 1800
    - width: 3800
  output_path_format: assets/resized/%{filename}-%{width}.%{extension}

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
