lang: ru
title: Михаил Юдин
headline: Михаил Юдин
author:
  name: Михаил Юдин
  email: fagci.nsk@gmail.com
logo: /assets/img/favicon-full.png
description: >
  Занимаюсь front-end разработкой, улучшаю UX. Рассказываю о железячных проектах, настройке сервера, полезных Android приложениях.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikhail-yudin.ru"

username:
  github: fagcinsk
  telegram: fagci
  vk: fagci
  skype: silenceproject
  twitter: fagcinsk
  facebook: fagcinsk
  icq: 430468782
  pinterest: fagcinsk
  instagram: fagci.nsk

social: # jekyll-seo-tag
  name: Михаил Юдин
  links:
    - https://twitter.com/fagcinsk
    - https://github.com/fagcinsk
    - https://vk.com/fagci
    - https://www.facebook.com/fagcinsk
    - https://www.instagram.com/fagci.nsk/

webmaster_verifications:
  google: cYPYXSNeHCFhzx8wb_DhIoSC1GhqibLCVUEDbpFfdgI
  yandex: ea38c54b7e1b64ef

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'codehilite'

sass:
  style: compressed

navigation: # Navigation links
  - {name: 'Проекты', link: '/projects/'}
  - {name: 'Обо мне', link: '/about/'}
  - {name: 'Контакты', link: '/contact/'}

permalinks: pretty
permalink: /:categories/:title/

categoryMap:
  frontend:
    name: Фронтенд
    description: "Материал, связанный с фронтовой частью веб-разработки: вёрстка, JavaScript, UX/UI в общем."
  backend:
    name: Бэкэнд
    description: "Бэкэндная часть веб-разработки: PHP, NodeJS, ..."
  lifehacks:
    name: Лайфхаки
    description: "Хитрости жизни"
  hardware:
    name: Железо
    description: "Железячные проекты: Arduino, STM32, всякие датчики, дисплеи, механизмы."
  linux:
    name: Linux
    description: "Администрирование Linux, настройка сервера, примеры настроек."
  android:
    name: Android
    description: "Приложения для Android, примеры использования приложений, обзоры, рекомендации."
  trip:
    name: Путешествия
    description: "Путешествия по необъятной планете =)"

leaflet: leaflet@1.5.1

autoprefixer:
  browsers:
    - last 2 versions

yandex_metrika:
  token: AgAAAAACBsTEAAXOQm6356MxwEN8vDlsI0f5t3g
  site_url: https://mikhail-yudin.ru/
  trim_last: " | Михаил Юдин"


#collections:
#  projects:
#    output: true
#    name: Проекты
#  posts:
#    output: false
#    name: Посты

pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  title: ':title - страница :num'
  category: 'posts'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2


autopages:
  enabled: true

  categories:
    layouts: ['autopage_category.html']
    title: ':cat'
    permalink: '/:cat'

#  collections:
#    layouts: ['autopage_collection.html']
#    title: 'Страницы в коллекции :coll'
#    permalink: '/collection/:coll'

#  tags:
#    layouts: ['autopage_tags.html']
#    title: 'Материалы с тегом :tag'
#    permalink: '/tag/:tag'

include:
  - _pages
  - _redirects
  - _projects

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .idea
  - .jekyll-cache
